// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FacilityEquipment struct {
	ID   uuid.UUID
	Name string
}

type FacilityLocation struct {
	ID        uuid.UUID
	Name      string
	Address   *string
	Timezone  string
	OpenTime  pgtype.Time
	CloseTime pgtype.Time
	CreatedAt time.Time
}

type FacilityRoom struct {
	ID          uuid.UUID
	LocationID  uuid.UUID
	Name        string
	Capacity    int32
	HourlyPrice int32
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type FacilityRoomEquipment struct {
	RoomID      uuid.UUID
	EquipmentID uuid.UUID
}

type IdentityUser struct {
	ID             uuid.UUID
	Email          string
	Name           string
	Provider       string
	ProviderUserID string
	Role           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ReservationOutbox struct {
	ID            int64
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
}

type ReservationReservation struct {
	ID             uuid.UUID
	RoomID         uuid.UUID
	UserID         uuid.UUID
	Title          string
	Attendees      int32
	Period         pgtype.Range[pgtype.Timestamptz]
	Status         string
	HoldExpiresAt  *time.Time
	CancelledAt    *time.Time
	IdempotencyKey *string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
