// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (name, email, provider, provider_user_id,role)
VALUES ($1, $2, $3, $4,$5)
RETURNING id, email, name, provider, provider_user_id, role, created_at, updated_at
`

type CreateUserParams struct {
	Name           string
	Email          string
	Provider       string
	ProviderUserID string
	Role           string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Provider,
		arg.ProviderUserID,
		arg.Role,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.ProviderUserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, email, name, provider, provider_user_id, role, created_at, updated_at FROM identity.users
WHERE provider = $1 AND provider_user_id = $2
`

type GetUserByProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByProvider, arg.Provider, arg.ProviderUserID)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.ProviderUserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
